import { describe, expect, it } from "vitest";
import { QuestionsRepository, pseudonymizeUserId } from "../src/storage/questions";
type Row = Record<string, unknown>;
class Statement { args: unknown[] = []; constructor(private db: FakeD1, private sql: string) {} bind(...a: unknown[]) { this.args = a; this.db.bound.push(a); return this; } first<T>() { return Promise.resolve(this.db.rows.get(String(this.args[0])) as T ?? null); } run() { return Promise.resolve(this.db.run(this.sql, this.args)); } }
class FakeD1 {
  rows = new Map<string, Row>(); bound: unknown[][] = []; prepare(sql: string) { return new Statement(this, sql); }
  run(sql: string, a: unknown[]) {
    if (sql.includes("INSERT INTO questions")) { const id = String(a[0]), old = this.rows.get(id); const reclaim = !old || old.status === "reply_failed" || old.status === "processing" && String(old.lease_until) <= String(a[2]); if (reclaim) this.rows.set(id, { ...old, webhook_event_id: id, status: "processing", lease_until: a[1], created_at: old?.created_at ?? a[2] }); return { success: true, meta: { changes: reclaim ? 1 : 0 } }; }
    if (sql.includes("UPDATE questions SET user_key")) { const row = this.rows.get(String(a[0])) ?? {}; Object.assign(row, { user_key: a[1], question: a[2], answer: a[3], status: sql.includes("status=?5") ? a[4] : row.status, model: sql.includes("status=?5") ? a[5] : a[4], prepared_status: sql.includes("status=?5") ? row.prepared_status : a[5], created_at: sql.includes("status=?5") ? a[6] : a[6], expires_at: sql.includes("status=?5") ? a[7] : a[7] }); this.rows.set(String(a[0]), row); return { success: true, meta: { changes: 1 } }; }
    if (sql.includes("DELETE FROM questions WHERE expires_at")) { let n = 0; for (const [id, row] of this.rows) if (String(row.expires_at) <= String(a[0])) { this.rows.delete(id); n++; } return { success: true, meta: { changes: n } }; }
    return { success: true, meta: { changes: 1 } };
  }
}
describe("QuestionsRepository", () => {
  it("claims first, returns busy/completed, and reclaims an expired lease", async () => { const db = new FakeD1(), repo = new QuestionsRepository(db as never, () => "2026-07-18T00:00:00.000Z"); expect(await repo.claim("e", "2026-07-18T00:01:00.000Z")).toEqual({ state: "claimed" }); expect(await repo.claim("e", "2026-07-18T00:01:00.000Z")).toEqual({ state: "busy" }); db.rows.get("e")!.lease_until = "2026-07-17T23:59:00.000Z"; expect(await repo.claim("e", "2026-07-18T00:01:00.000Z")).toEqual({ state: "claimed" }); db.rows.get("e")!.status = "answered"; expect(await repo.claim("e", "2026-07-18T00:01:00.000Z")).toEqual({ state: "completed" }); expect(db.bound.length).toBeGreaterThan(0); });
  it("pseudonymizes raw IDs with HMAC and supports unavailable IDs", async () => { const key = await pseudonymizeUserId("raw-user-id", "secret"); expect(key).toMatch(/^[a-f0-9]{64}$/); expect(key).not.toContain("raw-user-id"); expect(await pseudonymizeUserId(null, "secret")).toBeNull(); });
  it("retains exactly 30 days and purges only expired rows", async () => { const db = new FakeD1(), repo = new QuestionsRepository(db as never); const base = { userKey: null, question: "q", answer: "a", status: "answered" as const, model: "m" }; await repo.claim("old", "2026-06-18T00:01:00.000Z"); await repo.complete({ ...base, webhookEventId: "old", createdAt: "2026-06-18T00:00:00.000Z", expiresAt: "2026-07-18T00:00:00.000Z" }); await repo.claim("new", "2026-07-18T00:01:00.000Z"); await repo.complete({ ...base, webhookEventId: "new", createdAt: "2026-07-18T00:00:00.000Z", expiresAt: "2026-08-17T00:00:00.000Z" }); expect(Date.parse(String(db.rows.get("new")!.expires_at)) - Date.parse(String(db.rows.get("new")!.created_at))).toBe(30 * 86400_000); expect(await repo.purgeExpired("2026-07-18T00:00:00.000Z")).toBe(1); expect(db.rows.has("new")).toBe(true); });
});
